# Required
input:
  - traefik/values.yaml

draft: 2020
indent: 4
output: traefik/values.schema.json

schemaRoot:
  id: https://traefik.io/traefik-helm-chart.schema.json
  title: Traefik Proxy Helm Chart
  description: The Cloud Native Application Proxy
  additionalProperties: true
