apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 31.0.0
# renovate: image=traefik
appVersion: v3.1.3
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix(Traefik Hub): update CRDs to v1.5.0"
    - "fix(HTTP3): split udp and tcp Service when service.single is false"
    - "fix!: 🐛 set allowEmptyServices to true by default"
    - "feat(Traefik Hub): update CRDs to v1.7.0"
    - "chore(release): 🚀 publish v31.0.0"
