---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - traefik.io_ingressroutes.yaml
  - traefik.io_ingressroutetcps.yaml
  - traefik.io_ingressrouteudps.yaml
  - traefik.io_middlewares.yaml
  - traefik.io_middlewaretcps.yaml
  - traefik.io_serverstransports.yaml
  - traefik.io_serverstransporttcps.yaml
  - traefik.io_tlsoptions.yaml
  - traefik.io_tlsstores.yaml
  - traefik.io_traefikservices.yaml
